import { VehicleConfig, VehicleId } from './types';

export const VEHICLES: Record<VehicleId, VehicleConfig> = {
  car: {
    id: 'car',
    name: 'Hill Climber',
    tagline: 'Balanced all-rounder starter car',
    icon: '🚗',
    description: 'The classic balanced 2D hill climber. Reliable acceleration, moderate weight, and forgiving handling make it perfect for learning any course.',
    mass: 1.0,
    enginePower: 0.20,
    maxSpeed: 8.5,
    maxReverse: 3.8,
    brakePower: 0.16,
    airControl: 0.009,
    stability: 0.22,
    hillClimb: 1.0,
    suspensionStiffness: 0.40,
    rollingResistance: 0.985,
    wheels: [
      { offsetX: -24, offsetY: 6, radius: 12, isDrive: true },
      { offsetX: 24, offsetY: 6, radius: 12, isDrive: true },
    ],
    driver: {
      seatX: -6,
      seatY: -10,
      steeringX: 6,
      steeringY: -6,
      posture: 'car',
      headgear: 'cap',
      suitColor: '#3b82f6',
      helmetColor: '#1e293b',
      skinTone: '#fed7aa',
    },
    visual: {
      chassisWidth: 76,
      chassisHeight: 22,
      bodyColor: '#e63946',
      secondaryColor: '#1d3557',
      accentColor: '#f1faee',
      cabinColor: '#1d3557',
      wheelColor: '#1e293b',
      wheelRimColor: '#cbd5e1',
      hasRollCage: false,
      windowOpenProgress: 0,
    },
    stats: {
      speed: 6,
      power: 6,
      stability: 6,
      control: 7,
    },
    unlockRequirement: {
      type: 'free',
      value: 0,
      description: 'Default Starter Vehicle',
    },
  },

  scooter: {
    id: 'scooter',
    name: 'City Hopper',
    tagline: 'Agile & lightweight retro scooter',
    icon: '🛵',
    description: 'A nimble, lightweight scooter with upright rider ergonomics. Quick off the mark and easy to balance on rolling paths, though sensitive to hard jumps.',
    mass: 0.72,
    enginePower: 0.21,
    maxSpeed: 7.8,
    maxReverse: 3.2,
    brakePower: 0.17,
    airControl: 0.012,
    stability: 0.25,
    hillClimb: 1.05,
    suspensionStiffness: 0.44,
    rollingResistance: 0.986,
    wheels: [
      { offsetX: -20, offsetY: 7, radius: 10.5, isDrive: true },
      { offsetX: 21, offsetY: 7, radius: 10.5, isDrive: false },
    ],
    driver: {
      seatX: -5,
      seatY: -14,
      steeringX: 12,
      steeringY: -16,
      posture: 'scooter',
      headgear: 'helmet_retro',
      suitColor: '#06b6d4',
      helmetColor: '#e0f2fe',
      skinTone: '#fed7aa',
    },
    visual: {
      chassisWidth: 62,
      chassisHeight: 18,
      bodyColor: '#0ea5e9',
      secondaryColor: '#f0f9ff',
      accentColor: '#38bdf8',
      wheelColor: '#1e293b',
      wheelRimColor: '#f1f5f9',
    },
    stats: {
      speed: 5,
      power: 5,
      stability: 6,
      control: 8,
    },
    unlockRequirement: {
      type: 'level',
      value: 2,
      description: 'Complete Level 2 to unlock',
    },
  },

  tractor: {
    id: 'tractor',
    name: 'Iron Plough',
    tagline: 'High-torque agricultural powerhouse',
    icon: '🚜',
    description: 'Massive low-end torque and huge rear tread wheels let this heavy beast crawl up virtually any steep incline without slipping or rolling back.',
    mass: 1.45,
    enginePower: 0.27,
    maxSpeed: 6.4,
    maxReverse: 3.0,
    brakePower: 0.22,
    airControl: 0.006,
    stability: 0.35,
    hillClimb: 1.55,
    suspensionStiffness: 0.48,
    rollingResistance: 0.980,
    wheels: [
      { offsetX: -22, offsetY: 2, radius: 17, isDrive: true },
      { offsetX: 25, offsetY: 9, radius: 10, isDrive: false },
    ],
    driver: {
      seatX: -10,
      seatY: -18,
      steeringX: 6,
      steeringY: -15,
      posture: 'tractor',
      headgear: 'straw_hat',
      suitColor: '#15803d',
      helmetColor: '#fde047',
      skinTone: '#fbcfe8',
    },
    visual: {
      chassisWidth: 74,
      chassisHeight: 26,
      bodyColor: '#16a34a',
      secondaryColor: '#eab308',
      accentColor: '#15803d',
      wheelColor: '#0f172a',
      wheelRimColor: '#eab308',
    },
    stats: {
      speed: 4,
      power: 9,
      stability: 9,
      control: 5,
    },
    unlockRequirement: {
      type: 'coins',
      value: 150,
      description: 'Collect 150 total coins to unlock',
    },
  },

  jeep: {
    id: 'jeep',
    name: 'Dune Raider',
    tagline: 'Rugged 4x4 off-roader with steel cage',
    icon: '🚙',
    description: 'Equipped with heavy-duty knobby tires, an exposed safety roll cage, and firm off-road suspension. Masters rocky bumps and uneven crests with ease.',
    mass: 1.15,
    enginePower: 0.23,
    maxSpeed: 9.2,
    maxReverse: 4.2,
    brakePower: 0.19,
    airControl: 0.010,
    stability: 0.27,
    hillClimb: 1.25,
    suspensionStiffness: 0.42,
    rollingResistance: 0.985,
    wheels: [
      { offsetX: -25, offsetY: 5, radius: 13.5, isDrive: true },
      { offsetX: 25, offsetY: 5, radius: 13.5, isDrive: true },
    ],
    driver: {
      seatX: -7,
      seatY: -12,
      steeringX: 7,
      steeringY: -9,
      posture: 'jeep',
      headgear: 'bandana',
      suitColor: '#d97706',
      helmetColor: '#78350f',
      skinTone: '#fed7aa',
    },
    visual: {
      chassisWidth: 78,
      chassisHeight: 24,
      bodyColor: '#ea580c',
      secondaryColor: '#1e293b',
      accentColor: '#f97316',
      wheelColor: '#18181b',
      wheelRimColor: '#94a3b8',
      hasRollCage: true,
    },
    stats: {
      speed: 8,
      power: 8,
      stability: 8,
      control: 7,
    },
    unlockRequirement: {
      type: 'level',
      value: 3,
      description: 'Complete Level 3 to unlock',
    },
  },

  van: {
    id: 'van',
    name: 'Ridge Van',
    tagline: 'Heavy road cruiser with spacious cabin',
    icon: '🚐',
    description: 'A solid, heavyweight van with strong momentum. Absorbs road imperfections smoothly, but its heavy rear demands steady balance on big jump crests.',
    mass: 1.38,
    enginePower: 0.19,
    maxSpeed: 8.0,
    maxReverse: 3.5,
    brakePower: 0.18,
    airControl: 0.007,
    stability: 0.30,
    hillClimb: 1.10,
    suspensionStiffness: 0.38,
    rollingResistance: 0.984,
    wheels: [
      { offsetX: -27, offsetY: 6, radius: 12.5, isDrive: true },
      { offsetX: 27, offsetY: 6, radius: 12.5, isDrive: true },
    ],
    driver: {
      seatX: 12,
      seatY: -13,
      steeringX: 22,
      steeringY: -10,
      posture: 'van',
      headgear: 'beanie',
      suitColor: '#475569',
      helmetColor: '#e11d48',
      skinTone: '#fed7aa',
    },
    visual: {
      chassisWidth: 84,
      chassisHeight: 30,
      bodyColor: '#8b5cf6',
      secondaryColor: '#ede9fe',
      accentColor: '#7c3aed',
      cabinColor: '#4c1d95',
      wheelColor: '#1e293b',
      wheelRimColor: '#e2e8f0',
    },
    stats: {
      speed: 6,
      power: 6,
      stability: 8,
      control: 5,
    },
    unlockRequirement: {
      type: 'level',
      value: 4,
      description: 'Complete Level 4 to unlock',
    },
  },

  bike: {
    id: 'bike',
    name: 'Nitro Bike',
    tagline: 'High-speed stunt bike for daring racers',
    icon: '🏍️',
    description: 'Super-fast acceleration, blazing top speed, and extraordinary air rotation agility. Demands great landing precision, but delivers thrilling stunt air-time!',
    mass: 0.60,
    enginePower: 0.28,
    maxSpeed: 10.6,
    maxReverse: 3.6,
    brakePower: 0.20,
    airControl: 0.015,
    stability: 0.18,
    hillClimb: 1.20,
    suspensionStiffness: 0.45,
    rollingResistance: 0.988,
    wheels: [
      { offsetX: -24, offsetY: 6, radius: 13, isDrive: true },
      { offsetX: 24, offsetY: 6, radius: 13, isDrive: false },
    ],
    driver: {
      seatX: -6,
      seatY: -14,
      steeringX: 12,
      steeringY: -13,
      posture: 'bike',
      headgear: 'helmet_biker',
      suitColor: '#dc2626',
      helmetColor: '#18181b',
      skinTone: '#fed7aa',
    },
    visual: {
      chassisWidth: 68,
      chassisHeight: 20,
      bodyColor: '#ef4444',
      secondaryColor: '#171717',
      accentColor: '#facc15',
      wheelColor: '#18181b',
      wheelRimColor: '#f43f5e',
    },
    stats: {
      speed: 10,
      power: 8,
      stability: 4,
      control: 9,
    },
    unlockRequirement: {
      type: 'level',
      value: 5,
      description: 'Complete Level 5 to unlock',
    },
  },
};

export const VEHICLE_LIST: VehicleConfig[] = [
  VEHICLES.car,
  VEHICLES.scooter,
  VEHICLES.tractor,
  VEHICLES.jeep,
  VEHICLES.van,
  VEHICLES.bike,
];

export function isVehicleUnlocked(
  vehicle: VehicleConfig,
  unlockedLevels: number[],
  totalCoins: number,
  unlockedVehiclesList?: string[]
): boolean {
  if (unlockedVehiclesList && unlockedVehiclesList.includes(vehicle.id)) {
    return true;
  }
  const req = vehicle.unlockRequirement;
  if (req.type === 'free') return true;
  if (req.type === 'level') {
    return unlockedLevels.includes(req.value) || Math.max(...unlockedLevels, 1) >= req.value;
  }
  if (req.type === 'coins') {
    return totalCoins >= req.value;
  }
  return false;
}
